name: Ansible Deploy

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vm-ip

      - name: Read IP into ENV
        run: echo "VM_IP=$(cat vm_ip.txt)" >> $GITHUB_ENV

      - name: Add server to known_hosts
        run: ssh-keyscan -H "$VM_IP" >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        working-directory: ansible
        run: |
          ansible-playbook -i "$VM_IP," ansible/playbook.yml \
            --private-key ~/.ssh/id_ed25519 \
            -u azureuser
