name: Terraform Azure Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_ssh_public_key: ${{ secrets.VM_SSH_KEY_PUB }}

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Load SSH Key for VM
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
      - name: Init Terraform
        working-directory: terraform
        run: terraform init
        
      - name: Validate Terraform Format
        working-directory: terraform
        run: terraform fmt -check

      - name: Validate Terraform Config
        working-directory: terraform
        run: terraform validate

      - name: Import existing resource group (if needed)
        working-directory: terraform
        run: |
          terraform import azurerm_resource_group.main "/subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/cloud1-rg" || true

      - name: Plan Infra Changes
        working-directory: terraform
        run: terraform plan 

      - name: Apply Infra (only on push to main)
        working-directory: terraform
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
      - name: Get VM IP from Terraform Output
        working-directory: terraform
        id: tfoutput
        run: |
          echo "VM_IP=$(terraform output -raw vm_public_ip)" >> $GITHUB_ENV
      - name: Add server to known_hosts
        run: ssh-keyscan $VM_IP >> ~/.ssh/known_hosts

